### ISSUE TITLE
请教一个前后端交互的问题

### ISSUE THREAD

**Issue by miqitudou** [mowtwo/ffserver_frontend#3]
您好，我初学python web开发。我想请教一下您这个前端的代码是如何跟那边后端代码交互的呢，我看后端的部分没有你这里的代码。希望得到您的回复~

**Comment by mowtwo** [comment]
抱歉，这两天没有关注这里。
我们的项目本质上是一个前后端分离的项目，源码通过前端框架svelte进行编写，通信我采用的是前端fetch api进行通信（这种技术一般被称为ajax）。
但是为了方便一键部署，所以我将前端代码打包后嵌入到后端代码里，通过python提供的静态文件服务代理了前端的访问。

**Comment by mowtwo** [comment]
具体实现可以参考https://github.com/mowtwo/ffserver_frontend/blob/master/src/api/cmd.ts

**Comment by miqitudou** [comment]
谢谢您~
